trigger:
  branches:
    include:
    - main
stages:
- stage: __default
  jobs:
  - job: Job
    pool:
      name: Default
    steps:
    - task: CmdLine@2
      displayName: 'Run a one-line script'
      inputs:
        script: echo Hello, world!
    - task: DotNetCoreCLI@2
      inputs:
        command: 'custom'
        custom: 'list'
        arguments: 'package --vulnerable'
    - task: DotNetCoreCLI@2
      inputs:
        command: 'custom'
        custom: 'list'
        arguments: 'package --outdated'
    - task: CmdLine@2
      displayName: 'Run a multi-line script'
      inputs:
        script: |
          echo Add other tasks to build, test, and deploy your project.
          echo See https://aka.ms/yaml

