trigger:
- main

pool:
  name: Default

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'custom'
    custom: 'list'
    arguments: 'package --vulnerable'
- task: DotNetCoreCLI@2
  inputs:
    command: 'custom'
    custom: 'list'
    arguments: 'package --outdated'
